### ISSUE TITLE
Abstract all individual components into their own UserControl

### ISSUE THREAD

**Issue by Magdain** [Magdain/EmCaptions#12]
~~The Slider should be on the timeline.~~

~~The ListView should be its own control.~~

The Menu should be its own control, maybe?

~~Do something about ICommand boilerplate.~~

**Comment by wentimo** [comment]
Has everything on this issue been accomplished? If not what else needs done?

**Comment by Magdain** [comment]
making the menu it's own thing is complicated because it interacts with so much of the data on the editorwindow.  probably possible, not sure if it would be an improvement, depending on how much convoluted shit needs to be done
